### ISSUE TITLE
Styles for the close button are not recognised

### ISSUE THREAD

**Issue by JuaniVega** [FlowingCode/GraniteAlertAddon#17]
After adding the GraniteAlert 2.0.0 dependency for Vaadin 23.2.1, I try to add a new alert to the view, as shown in the demo, and the styles for the "close" button are not recognised.

![image](https://github.com/FlowingCode/GraniteAlertAddon/assets/63079743/be6edfad-600e-4274-b5c7-012cc67851e2)

**Comment by javier-godoy** [comment]
Hello. This add-on only provides alert bars. The button styles shown in the demo are intentionally not included in add-on, because GranitAlert does not take any decision on how to style any component added to the alert.

https://github.com/FlowingCode/GraniteAlertAddon/blob/b2e63042aa4c22ea97eac579ef248bc80fac3954/src/test/resources/META-INF/resources/frontend/styles/granitealert/demo-styles.css#L20-L27
